= Application Deployment

== Image Change Playground

```sh
# deploy the example
oc apply -f - <<EOF
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: builder-test
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: builder-test
  name: builder-test
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: builder-test:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: "FROM rhscl/s2i-base-rhel7:latest \nENTRYPOINT bash\n"
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/rhscl/s2i-base-rhel7:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: builder-test
  name: builder-test
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: builder-test
    deploymentconfig: builder-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: builder-test
        deploymentconfig: builder-test
    spec:
      containers:
      - image: builder-test:latest
        imagePullPolicy: Always
        name: builder-test
        command:
        - /bin/sh
        - -c
        - while true ; do date; sleep 1; done;
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - builder-test
      from:
        kind: ImageStreamTag
        name: builder-test:1.0
    type: ImageChange
EOF
```

```sh
# start the build and check that DC is not starting
$ oc start-build builder-test
```

```sh
# tag the is and check that dc is starting up
$ oc tag builder-test:latest builder-test:1.0
```

== Zero downtime canary deployment

We'll see how OpenShift can help you execute a canary deployment. The same method can also be used for blue-green deployments.

=== Deploy Prod App
First of all deploy an example application hello-openshift called prod by creating a deployment configuration object (DC):

```sh
$ oc apply -f - <<EOF
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: prod
  namespace: canary
spec:
  selector:
    app: prod
  replicas: 3
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
        - name: prod
          image: >-
            docker.io/openshift/hello-openshift:latest
          ports:
            - containerPort: 8080
EOF
```

Reconfigure the application to reply differently by changing the environment in the DC:

```sh
$ oc set env dc/prod RESPONSE="Hello from Prod"
```

This will re-deploy the application. The 3 pods will be replaced.

Create a service object by exposing the DC:

```sh
$ oc expose dc/prod --port=8080
```

Expose the application externally, creating a route:

```sh
$ oc expose svc/prod
$ oc get route
```
=== Deploy Canary App

Add a new version of the application, called canary:

```sh
$ oc apply -f - <<EOF
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: canary
  namespace: canary
spec:
  selector:
    app: canary
  replicas: 3
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
        - name: canary
          image: >-
            docker.io/openshift/hello-openshift:latest
          ports:
            - containerPort: 8080
EOF
```

Set the canary version of the application to reply differently:

```sh
$ oc set env dc/canary RESPONSE="Hello from Canary"
$ oc expose dc/canary --port=8080
```

Set all traffic to go to the current version, prod:

```sh
$ oc set route-backends prod prod=100 canary=0
```

=== Show canary deployment

Fetch the route into a variable you can use later:

```sh
$ APP_ROUTE=`oc get route prod -o jsonpath='{.spec.host}{"\n"}'`; echo $APP_ROUTE
```

Test the application, showing that all requests are sent to the production version:

```sh
for i in {0..15}; do curl http://$APP_ROUTE/; sleep .2; done
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
```

Now configure it so that 10% of requests are sent to the canary version of the application:

```sh
$ oc set route-backends prod prod=90 canary=10
```

Test the application, showing that 90% of requests are sent to the production version and 10% are sent to the canary version:

```sh
$ for i in {0..15}; do curl http://$APP_ROUTE/; sleep .2; done
Hello from Canary
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Canary
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
Hello from Prod
```